{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "evpn-agent.fullname" .) .Values.serviceAccount.name }}
  labels:
    {{- include "evpn-agent.labels" . | nindent 4 }}
{{- end -}}
