image:
  repository: hostfw-local.artifactory-espoo1.int.net.nokia.com/release/evpn-agent
  tag: dev
  pullPolicy: IfNotPresent

agent:
  logLevel: info
  advertiseSelf: true
  communityAsn: 65000
  gobgpAddress: 127.0.0.1:50051
  gobgpTimeout: 5s
  localInterface: eth0
  localAddress: ""
  vxlanPort: 4789
  skipLinkCleanup: false
  autoRecreateVxlan: false

gobgp:
  enabled: true
  image: jauderho/gobgp
  tag: v3.28.0
  pullPolicy: IfNotPresent
  asn: 65001
  logLevel: info
  multihopTtl: 8
  routerID: ""
  neighbors: []
  dynamic:
    enabled: false
    prefix: ""    # e.g. "10.244.0.0/16"
    peerAs: 65000
  rr:
    enabled: false
    client: false
  routeServer:
    enabled: false
  # Example:
  # neighbors:
  #   - address: 10.244.2.11
  #     asn: 65002
  #     multihopTtl: 8

serviceAccount:
  create: true
  name: ""

podAnnotations: {}
nodeSelector: {}
affinity: {}
tolerations: []
priorityClassName: ""
hostNetwork: false

replicas: 2

securityContext:
  privileged: true
  capabilities:
    add: ["NET_ADMIN", "NET_RAW"]

init:
  image:
    repository: busybox
    tag: "1.36"

fullnameOverride: ""

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
